version: "3.7"

services:
  redis:
    image: redis:alpine
    networks:
      - backend

  duckling:
    image: rasa/duckling
    ports:
      - "8000:8000"
    networks:
      - backend

  actions:
    image: sara-actions:latest
    ports:
      - "5055:5055"
    deploy:
      replicas: 1

  bot:
    image: sara-bot:latest
    ports:
      - "5005:5005"
    networks:
      - backend
    environment:
      - MAX_NUMBER_OF_PREDICTIONS=100
      - TICKET_LOCK_LIFETIME=60
      - SANIC_WORKERS=1
      - SANIC_BACKLOG=200
      - RASA_DUCKLING_HTTP_URL=http://duckling:8000
    depends_on:
      - duckling
      - redis
      - actions
    deploy:
      replicas: 1

  ui:
    image: sara-ui:latest
    networks:
      - backend
      - frontend
    ports:
      - "80:80"

networks:
  frontend:
  backend:

